### ISSUE TITLE
Update Atomics.wait to call DoWait?

### ISSUE THREAD

**Issue by rwaldron** [tc39/proposal-atomics-wait-async#21]
With the introduction of the new abstract operation `DoWait()` that accepts a mode of `async` or `sync`, I would expect the algorithm steps in `Atomics.wait` to be replaced with: 

> 1. Return DoWait(sync, typedArray, index, value, timeout).

**Comment by syg** [comment]
Yeah, I guess it should. Originally I preferred not refactoring out a common AO since the branching on sync and async made it harder to read. But... then I committed the refactor anyway? So I must have changed my mind? Been a while.
