### ISSUE TITLE
Step 12.a. should set, not let

### ISSUE THREAD

**Issue by rwaldron** [tc39/proposal-atomics-wait-async#23]
Currently: 

> 11. Let promiseCapability be undefined.
> 12. If mode is async, then
>        a. Let promiseCapability be ! NewPromiseCapability(%Promise%).

Should be: 

> 11. Let promiseCapability be undefined.
> 12. If mode is async, then
>        a. Set promiseCapability to ! NewPromiseCapability(%Promise%).

**Comment by syg** [comment]
Good catch, will fix.
